// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class EmpStat01Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void empStat01() {
    driver.get("https://hypershop-scys.onrender.com/account/login");
    driver.findElement(By.cssSelector(".input:nth-child(1)")).click();
    driver.findElement(By.xpath("//input")).click();
    driver.findElement(By.xpath("//input")).sendKeys("010203040506");
    driver.findElement(By.xpath("//input[@type=\'password\']")).click();
    driver.findElement(By.xpath("//input[@type=\'password\']")).sendKeys("123456@aA");
    driver.findElement(By.xpath("//div[5]")).click();
    driver.findElement(By.xpath("//span[contains(.,\'Không đổi\')]")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//div[contains(@class,\'text\') and contains(@class,\'module-parent\') and normalize-space(.)=\'Quản lý tài khoản\']")));
    }
    driver.findElement(By.xpath("//div[contains(@class,\'text\') and contains(@class,\'module-parent\') and normalize-space(.)=\'Quản lý tài khoản\']")).click();
    driver.findElement(By.xpath("//div[contains(@class,\'item-submodule\') and normalize-space(.)=\'Thông tin nhân viên\']")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//div[contains(@class,\'block\') and .//div[contains(@class,\'text\') and normalize-space(@title)=\'Bill Manager\']]")));
    }
    driver.findElement(By.xpath("//div[contains(@class,\'block\') and .//div[contains(@class,\'text\') and normalize-space(@title)=\'Bill Manager\']]")).click();
    driver.findElement(By.xpath("//div[contains(@class,\'text\') and contains(@class,\'ng-tns-c2722795579-1\') and normalize-space(.)=\'Tổng số lượng tài khoản\']")).click();
    vars.put("num", js.executeScript("return (function(){var curr=document.evaluate(\"count(//div[contains(@class,\'value\')])\",document,null,XPathResult.NUMBER_TYPE,null).numberValue; var prev=parseInt(\'arguments[0]\',10); if(isNaN(prev)) prev=0; return prev+curr; })();", vars.get("num")));
    driver.findElement(By.xpath("//button[@title=\'Page 2\' and contains(@class,\'k-pager-nav\') and .//span[normalize-space(.)=\'2\']]")).click();
    vars.put("num", js.executeScript("return (function(){var curr=document.evaluate(\"count(//div[contains(@class,\'value\')])\",document,null,XPathResult.NUMBER_TYPE,null).numberValue; var prev=parseInt(\'arguments[0]\',10); if(isNaN(prev)) prev=0; return prev+curr; })();", vars.get("num")));
    driver.findElement(By.xpath("//button[@title=\'Page 3\' and contains(@class,\'k-pager-nav\') and .//span[normalize-space(.)=\'3\']]")).click();
    vars.put("num", js.executeScript("return (function(){var curr=document.evaluate(\"count(//div[contains(@class,\'value\')])\",document,null,XPathResult.NUMBER_TYPE,null).numberValue; var prev=parseInt(\'arguments[0]\',10); if(isNaN(prev)) prev=0; return prev+curr; })();", vars.get("num")));
    assertThat(driver.findElement(By.xpath("//div[contains(@class,\'value\') and contains(@class,\'ng-tns-c2722795579-2\')]")).getText(), is(not("vars.get(\"num\").toString()")));
  }
}
