// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ProductList06Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void productList06() {
    driver.get("https://hypershop-scys.onrender.com/account/login");
    driver.findElement(By.cssSelector(".input:nth-child(1)")).click();
    driver.findElement(By.xpath("//input")).click();
    driver.findElement(By.xpath("//input")).sendKeys("010203040506");
    driver.findElement(By.xpath("//input[@type=\'password\']")).click();
    driver.findElement(By.xpath("//input[@type=\'password\']")).sendKeys("123456@aA");
    driver.findElement(By.xpath("//div[5]")).click();
    driver.findElement(By.xpath("//span[contains(.,\'Không đổi\')]")).click();
    driver.findElement(By.xpath("//li[2]/div/div")).click();
    driver.findElement(By.xpath("//li[2]/div[2]")).click();
    driver.findElement(By.xpath("//div[normalize-space(.)=\'Sản phẩm ngưng kinh doanh\']")).click();
    driver.findElement(By.xpath("//div[normalize-space(.)=\'Sản phẩm đang kinh doanh\']")).click();
    driver.findElement(By.xpath("//div[normalize-space(.)=\'Sản phẩm Unisex\']")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//div[normalize-space(.)=\'Ngừng kinh doanh\']")));
    }
    vars.put("ngungCount", driver.findElements(By.xpath("//div[normalize-space(.)=\'Ngừng kinh doanh\']")).size());
    System.out.println(vars.get("ngungCount").toString());
    assertThat(driver.findElement(By.xpath("//div[@class=\'value ng-tns-c2722795579-2\']")).getText(), is("vars.get(\"ngungCount\").toString()"));
  }
}
