// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ProductList03Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void productList03() {
    driver.get("https://hypershop-scys.onrender.com/account/login");
    driver.findElement(By.cssSelector(".input:nth-child(1)")).click();
    driver.findElement(By.xpath("//input")).click();
    driver.findElement(By.xpath("//input")).sendKeys("010203040506");
    driver.findElement(By.xpath("//input[@type=\'password\']")).click();
    driver.findElement(By.xpath("//input[@type=\'password\']")).sendKeys("123456@aA");
    driver.findElement(By.xpath("//div[5]")).click();
    driver.findElement(By.xpath("//span[contains(.,\'Không đổi\')]")).click();
    driver.findElement(By.xpath("//li[2]/div/div")).click();
    driver.findElement(By.xpath("//li[2]/div[2]")).click();
    driver.findElement(By.cssSelector(".k-master-row:nth-child(1) .idproduct")).click();
    driver.findElement(By.cssSelector(".k-master-row:nth-child(1) .component-button")).click();
    driver.findElement(By.cssSelector(".ng-star-inserted:nth-child(1) > component-button .ng-star-inserted:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".active .component-button")).click();
    driver.findElement(By.cssSelector(".ng-star-inserted:nth-child(1) > component-button .ng-star-inserted:nth-child(2)")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 3);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//span[normalize-space(.)=\'Sneakers\']")));
    }
    driver.findElement(By.xpath("//span[normalize-space(.)=\'Sneakers\']")).click();
    driver.findElement(By.xpath("//span[normalize-space(.)=\'Giày da\']")).click();
    driver.findElement(By.xpath("//span[normalize-space(.)=\'Nữ\']")).click();
    driver.findElement(By.xpath("//span[normalize-space(.)=\'Nam\']")).click();
    driver.findElement(By.cssSelector(".button-update #idIconFontAwsome")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.xpath("//div[text()=\'Giày da\']")).click();
    assertThat(driver.findElement(By.xpath("//div[text()=\'Giày da\']")).getText(), is("Giày da"));
    driver.findElement(By.xpath("//div[text()=\'Nam\']")).click();
    assertThat(driver.findElement(By.xpath("//div[text()=\'Nam\']")).getText(), is("Nam"));
  }
}
