// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ProductList04Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void productList04() {
    driver.get("https://hypershop-scys.onrender.com/account/login");
    driver.findElement(By.cssSelector(".input:nth-child(1)")).click();
    driver.findElement(By.xpath("//input")).click();
    driver.findElement(By.xpath("//input")).sendKeys("010203040506");
    driver.findElement(By.xpath("//input[@type=\'password\']")).click();
    driver.findElement(By.xpath("//input[@type=\'password\']")).sendKeys("123456@aA");
    driver.findElement(By.xpath("//div[5]")).click();
    driver.findElement(By.xpath("//span[contains(.,\'Không đổi\')]")).click();
    driver.findElement(By.xpath("//li[2]/div/div")).click();
    driver.findElement(By.xpath("//li[2]/div[2]")).click();
    driver.findElement(By.xpath("//span[text()=\'Thêm mới\']")).click();
    driver.findElement(By.cssSelector("input[placeholder=\'Nhập mã sản phẩm...\']")).click();
    driver.findElement(By.cssSelector("input[placeholder=\'Nhập mã sản phẩm...\']")).sendKeys("AUTO_007");
    driver.findElement(By.cssSelector("input[placeholder=\'Nhập tên sản phẩm...\']")).click();
    driver.findElement(By.cssSelector("input[placeholder=\'Nhập tên sản phẩm...\']")).sendKeys("Giày Thể Thao Cao Cấp Alpha 2.0");
    driver.findElement(By.xpath("//span[normalize-space(.)=\'-- Màu sắc --\']")).click();
    driver.findElement(By.xpath("//span[normalize-space(.)=\'Đen\']")).click();
    driver.findElement(By.xpath("//span[normalize-space(.)=\'-- Loại sản phẩm --\']")).click();
    driver.findElement(By.xpath("//span[normalize-space(.)=\'Sneakers\']")).click();
    driver.findElement(By.xpath("//span[normalize-space(.)=\'-- Thương hiệu --\']")).click();
    driver.findElement(By.xpath("//span[normalize-space(.)=\'Nike\']")).click();
    driver.findElement(By.xpath("//span[normalize-space(.)=\'-- Giới tính --\']")).click();
    driver.findElement(By.xpath("//span[normalize-space(.)=\'Nam\']")).click();
    driver.findElement(By.xpath("//label[normalize-space(.)=\'Giá sản phẩm\']/following::input[1]")).click();
    driver.findElement(By.xpath("//label[normalize-space(.)=\'Giá sản phẩm\']/following::input[1]")).sendKeys("  ");
    driver.findElement(By.xpath("//label[normalize-space(.)=\'Giá sản phẩm\']/following::input[1]")).sendKeys("250000");
    driver.findElement(By.xpath("//label[normalize-space(.)=\'Giảm giá theo phần trăm (%)\']/following::input[1]")).click();
    driver.findElement(By.xpath("//label[normalize-space(.)=\'Giảm giá theo phần trăm (%)\']/following::input[1]")).sendKeys("10");
    driver.findElement(By.xpath("//textarea[@placeholder=\'Vui lòng nhập...\']")).click();
    driver.findElement(By.xpath("//textarea[@placeholder=\'Vui lòng nhập...\']")).sendKeys("Giày chạy bộ chuyên nghiệp, siêu nhẹ, đệm đàn hồi cao.");
    driver.findElement(By.xpath("//label[normalize-space(.)=\'Size 40\']/following::input[1]")).click();
    driver.findElement(By.xpath("//label[normalize-space(.)=\'Size 40\']/following::input[1]")).sendKeys("50");
    driver.findElement(By.xpath("//label[normalize-space(.)=\'Size 41\']/following::input[1]")).click();
    driver.findElement(By.xpath("//label[normalize-space(.)=\'Size 41\']/following::input[1]")).sendKeys("60");
    driver.findElement(By.xpath("//label[normalize-space(.)=\'Size 42\']/following::input[1]")).click();
    driver.findElement(By.xpath("//label[normalize-space(.)=\'Size 42\']/following::input[1]")).sendKeys("50");
    driver.findElement(By.xpath("//label[normalize-space(.)=\'Size 43\']/following::input[1]")).click();
    driver.findElement(By.xpath("//label[normalize-space(.)=\'Size 43\']/following::input[1]")).sendKeys("40");
    System.out.println("   ");
    driver.findElement(By.xpath("//span[text()=\'Thêm mới\']")).click();
  }
}
